services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/data:/app/data
      - ./backend/migrations:/app/migrations
      - ./backend/alembic.ini:/app/alembic.ini
      - ./backend/main.py:/app/main.py
      - ./backend/models.py:/app/models.py
      - ./backend/schemas.py:/app/schemas.py
      - ./backend/crud.py:/app/crud.py
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=sqlite:////app/data/ipam.db
    cap_add:
      - NET_ADMIN
    # command: sh -c "uv run alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # volumes:
    #   - ./frontend:/app
    #   - /app/node_modules # Don't sync node_modules from host
    ports:
      - "8080:80"
    depends_on:
      - backend
